apiVersion: v1
kind: Service
metadata:
  name: kieker-bridge
  labels:
    app: kieker-bridge
spec:
  selector:
    app: kieker-bridge
  ports:
    - name: tcp
      port: 10001
      targetPort: 10001
      protocol: TCP
    - name: metrics
      port: 9465
      targetPort: 9465
      protocol: TCP
