apiVersion: v1
kind: Service
metadata:
  name: teastore-recommender
  labels:
    app: teastore
    run: teastore-recommender
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: teastore
    run: teastore-recommender
