apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  labels:
    app: teastore
    run: teastore-persistence
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: teastore
    run: teastore-persistence
