apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: teastore
    run: teastore-auth
