apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: teastore
        run: teastore-webui
    spec:
      terminationGracePeriodSeconds: 0

      initContainers:
        - name: wait-for-teastore-image
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for teastore-image service to be ready..."
              until nc -z teastore-image 8080; do
                echo "Still waiting for teastore-image..."
                sleep 3
              done
              echo "teastore-image is ready!"
        - name: wait-for-kieker-bridge
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for kieker-bridge service to be ready..."
              until nc -z kieker-bridge 10001; do
                echo "Still waiting for kieker-bridge on port 10001..."
                sleep 3
              done
              echo "kieker-bridge is ready!"
      containers:
        - name: teastore-webui
          image: "{{ .Values.image.webui }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            - name: HOST_NAME
              value: "teastore-webui"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: RABBITMQ_HOST
              value: "teastore-rabbitmq"

          volumeMounts:
            - name: kieker-config-volume
              mountPath: /kieker/config/kieker.monitoring.properties
              subPath: kieker.monitoring.properties

          resources:
            requests:
              cpu: {{ .Values.webui.resources.requests.cpu }}
              memory: {{ .Values.webui.resources.requests.memory }}
            limits:
              cpu: {{ .Values.webui.resources.limits.cpu }}
              memory: {{ .Values.webui.resources.limits.memory }}

      volumes:
        - name: kieker-config-volume
          configMap:
            name: kieker-config
