apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: {{ .Values.webui.serviceType }}
  ports:
    - name: http
      port: {{ .Values.service.port  }}
      targetPort: {{ .Values.service.port  }}
      protocol: TCP
      nodePort: {{ .Values.webui.nodePort }}
  selector:
    app: teastore
    run: teastore-webui
