apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
  labels:
    app: explorviz
    run: collaboration-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: explorviz
    run: collaboration-service
  ports:
    - name: http
      port: {{ .Values.collaboration.port }}
      targetPort: http
      protocol: TCP
