apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: explorviz
    run: frontend
spec:
  type: NodePort
  selector:
    app: explorviz
    run: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
