apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app: explorviz
    run: grafana
data:
{{ (.Files.Glob "files/monitoring/grafana/provisioning/**").AsConfig | indent 2 }}