apiVersion: v1
kind: Service
metadata:
  name: kafka-lag-exporter
  labels:
    app: explorviz
    run: kafka-lag-exporter
spec:
  type: {{ .Values.service.type}}
  selector:
    app: explorviz
    run: kafka-lag-exporter
  ports:
    - name: metrics
      port: {{ .Values.kafkaLagExporter.port }}
      targetPort: {{ .Values.kafkaLagExporter.port }}
