apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: explorviz
    run: kafka
spec:
  clusterIP: None  # Needed for StatefulSet to have stable DNS
  selector:
    app: explorviz
    run: kafka
  ports:
    - name: internal
      port: {{ .Values.kafka.ports.internal }}
      targetPort: {{ .Values.kafka.ports.internal }}
    - name: external
      port: {{ .Values.kafka.ports.external }}
      targetPort: {{ .Values.kafka.ports.external }}
    # - name: controller
    #   port: {{ .Values.kafka.ports.controller }}
    #   targetPort: {{ .Values.kafka.ports.controller }}
    - name: jmx
      port: {{ .Values.kafka.ports.jmx }}
      targetPort: {{ .Values.kafka.ports.jmx }}
