apiVersion: v1
kind: Service
metadata:
  name: mongo-user
  labels:
    app: explorviz
    run: mongo-user
spec:
  clusterIP: None  
  selector:
    app: explorviz
    run: mongo-user
  ports:
    - name: mongo
      port: {{ .Values.mongoUser.port }}
      targetPort: {{ .Values.mongoUser.port }}
