apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: explorviz
    run: otel-collector
spec:
  type: ClusterIP
  selector:
    app: explorviz
    run: otel-collector
  ports:
    - name: otlp
      port: {{ .Values.otelCollector.ports.main }}
      targetPort: {{ .Values.otelCollector.ports.main }}
    - name: zpages
      port: {{ .Values.otelCollector.ports.zpages }}
      targetPort: {{ .Values.otelCollector.ports.zpages }}
