apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: explorviz
    run: prometheus
spec:
  type: {{ .Values.service.type }}
  selector:
    app: explorviz
    run: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
