apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: explorviz
    run: schema-registry
spec:
  type: {{ .Values.service.type }}
  selector:
    app: explorviz
    run: schema-registry
  ports:
    - name: http
      port: {{ .Values.schemaRegistry.port }}
      targetPort: {{ .Values.schemaRegistry.port }}
